insert into quizzes (owner_id, title, description) values (1, 'Delissea sinuata Hillebr.', 'Nesomimus trifasciatus');
insert into quizzes (owner_id, title, description) values (2, 'Begonia convolvulacea A. DC.', 'Plegadis ridgwayi');
insert into quizzes (owner_id, title, description) values (3, 'Anagallis minima (L.) Krause', 'Leptoptilos crumeniferus');
insert into quizzes (owner_id, title, description) values (4, 'Helocarpon Th. Fr.', 'Tayassu tajacu');
insert into quizzes (owner_id, title, description) values (5, 'Acalypha ostryifolia Riddell', 'Lasiodora parahybana');
insert into quizzes (owner_id, title, description) values (6, 'Salvia verticillata L.', 'Phoca vitulina');
insert into quizzes (owner_id, title, description) values (7, 'Pertusaria floridana Dibben', 'Spermophilus parryii');
insert into quizzes (owner_id, title, description) values (8, 'Pithecoctenium crucigerum (L.) A.H. Gentry', 'Agouti paca');
insert into quizzes (owner_id, title, description) values (9, 'Piriqueta cistoides (L.) Griseb.', 'Trichosurus vulpecula');
insert into quizzes (owner_id, title, description) values (10, 'Justicia carthagenensis Jacq.', 'Pytilia melba');
insert into quizzes (owner_id, title, description) values (11, 'Tripterocalyx micranthus (Torr.) Hook.', 'Laniaurius atrococcineus');
insert into quizzes (owner_id, title, description) values (12, 'Agrostis clavata Trin.', 'Macaca mulatta');
insert into quizzes (owner_id, title, description) values (13, 'Calylophus tubicula (A. Gray) P.H. Raven', 'Rhea americana');
insert into quizzes (owner_id, title, description) values (14, 'Pertusaria excludens Nyl.', 'Macropus fuliginosus');
insert into quizzes (owner_id, title, description) values (15, 'Tayloria serrata (Hedw.) Bruch & Schimp.', 'Bucorvus leadbeateri');
insert into quizzes (owner_id, title, description) values (16, 'Phyllanthus ericoides Torr.', 'Cereopsis novaehollandiae');
insert into quizzes (owner_id, title, description) values (17, 'Eucalyptus propinqua H. Deane & Maiden', 'Lamprotornis chalybaeus');
insert into quizzes (owner_id, title, description) values (18, 'Ipomopsis roseata (Rydb.) V.E. Grant', 'Ratufa indica');
insert into quizzes (owner_id, title, description) values (19, 'Centrosema (DC.) Benth.', 'Haliaetus leucogaster');
insert into quizzes (owner_id, title, description) values (20, 'Mitella L.', 'Spilogale gracilis');
insert into quizzes (owner_id, title, description) values (21, 'Turnera diffusa Willd. ex Schult.', 'Porphyrio porphyrio');
insert into quizzes (owner_id, title, description) values (22, 'Orthothecium intricatum (Hartm.) Schimp.', 'Nasua nasua');
insert into quizzes (owner_id, title, description) values (23, 'Caulanthus crassicaulis (Torr.) S. Watson var. glaber M.E. Jones', 'Stenella coeruleoalba');
insert into quizzes (owner_id, title, description) values (24, 'Capsicum annuum L. var. glabriusculum (Dunal) Heiser & Pickersgill', 'Cacatua tenuirostris');
insert into quizzes (owner_id, title, description) values (25, 'Sisymbrium polyceratium L.', 'Varanus komodensis');
insert into quizzes (owner_id, title, description) values (26, 'Carex serratodens W. Boott', 'unavailable');
insert into quizzes (owner_id, title, description) values (27, 'Mertensia Roth', 'Canis mesomelas');
insert into quizzes (owner_id, title, description) values (28, 'Dalea jamesii (Torr.) Torr. & A. Gray', 'Ara macao');
insert into quizzes (owner_id, title, description) values (29, 'Browallia eludens R.K. Van Devender & P.D. Jenkins', 'Nectarinia chalybea');
insert into quizzes (owner_id, title, description) values (30, 'Rosa virginiana Mill.', 'Sula nebouxii');
insert into quizzes (owner_id, title, description) values (31, 'Hieracium canadense Michx.', 'unavailable');
insert into quizzes (owner_id, title, description) values (32, 'Sansevieria hyacinthoides (L.) Druce', 'Anastomus oscitans');
insert into quizzes (owner_id, title, description) values (33, 'Thelignya lignyota (Wahlenb.) P.M. Jørg. & Henssen', 'Panthera pardus');
insert into quizzes (owner_id, title, description) values (34, 'Barbula agraria Hedw.', 'Corvus albus');
insert into quizzes (owner_id, title, description) values (35, 'Draba asterophora Payson var. asterophora', 'Ciconia episcopus');
insert into quizzes (owner_id, title, description) values (36, 'Pulsatilla occidentalis (S. Watson) Freyn', 'Tragelaphus strepsiceros');
insert into quizzes (owner_id, title, description) values (37, 'Allium canadense L.', 'Streptopelia decipiens');
insert into quizzes (owner_id, title, description) values (38, 'Astragalus newberryi A. Gray var. newberryi', 'Bettongia penicillata');
insert into quizzes (owner_id, title, description) values (39, 'Peperomia rockii C. DC.', 'Milvus migrans');
insert into quizzes (owner_id, title, description) values (40, 'Cryptantha circumscissa (Hook. & Arn.) I.M. Johnst. var. circumscissa', 'Ardea golieth');
insert into quizzes (owner_id, title, description) values (41, 'Pertusaria octomela (Norman) Erichsen', 'Phalacrocorax niger');
insert into quizzes (owner_id, title, description) values (42, 'Prunus L.', 'Lorythaixoides concolor');
insert into quizzes (owner_id, title, description) values (43, 'Pseudephebe M. Choisy', 'Bucorvus leadbeateri');
insert into quizzes (owner_id, title, description) values (44, 'Keckiella breviflora (Lindl.) Straw ssp. breviflora', 'Ciconia ciconia');
insert into quizzes (owner_id, title, description) values (45, 'Lasianthaea podocephala (A. Gray) K. Becker', 'Oryx gazella');
insert into quizzes (owner_id, title, description) values (46, 'Agastache pringlei (Briq.) Lint & Epling', 'Bison bison');
insert into quizzes (owner_id, title, description) values (47, 'Ticanto nuga (L.) Medik.', 'Anas punctata');
insert into quizzes (owner_id, title, description) values (48, 'Clarkia borealis E. Small ssp. borealis', 'Epicrates cenchria maurus');
insert into quizzes (owner_id, title, description) values (49, 'Koenigia L.', 'Ploceus intermedius');
insert into quizzes (owner_id, title, description) values (50, 'Phragmites karka (Retz.) Trin. ex Steud. [excluded]', 'Alouatta seniculus');
insert into quizzes (owner_id, title, description) values (51, 'Amsinckia carinata A. Nelson & J.F. Macbr.', 'Isoodon obesulus');
insert into quizzes (owner_id, title, description) values (52, 'Phacelia minor (Harv.) Thell.', 'Carduelis pinus');
insert into quizzes (owner_id, title, description) values (53, 'Mammea L.', 'Macropus agilis');
insert into quizzes (owner_id, title, description) values (54, 'Deinandra corymbosa (DC.) B.G. Baldw. ssp. corymbosa', 'Merops bullockoides');
insert into quizzes (owner_id, title, description) values (55, 'Plantago argyrea Morris', 'Pan troglodytes');
insert into quizzes (owner_id, title, description) values (56, 'Dulichium arundinaceum (L.) Britton var. boreale Lepage', 'Papilio canadensis');
insert into quizzes (owner_id, title, description) values (57, 'Stenochlaena J. Sm.', 'Lamprotornis superbus');
insert into quizzes (owner_id, title, description) values (58, 'Nissolia Jacq.', 'Arctogalidia trivirgata');
insert into quizzes (owner_id, title, description) values (59, 'Halimolobos mollis (Hook.) Rollins', 'Butorides striatus');
insert into quizzes (owner_id, title, description) values (60, 'Lycopodium ×issleri (Rouy) Domin', 'Colaptes campestroides');
insert into quizzes (owner_id, title, description) values (61, 'Oxytheca emarginata H.M. Hall', 'Threskionis aethiopicus');
insert into quizzes (owner_id, title, description) values (62, 'Arctostaphylos gabilanensis V.T. Parker & M.C. Vasey', 'Amblyrhynchus cristatus');
insert into quizzes (owner_id, title, description) values (63, 'Aspicilia leprosescens (Sandst.) Hav.', 'Hystrix indica');
insert into quizzes (owner_id, title, description) values (64, 'Cyclodictyon Mitt.', 'Canis mesomelas');
insert into quizzes (owner_id, title, description) values (65, 'Tolumnia bahamensis (Nash ex Britton & Millsp.) G.J. Braem', 'Pterocles gutturalis');
insert into quizzes (owner_id, title, description) values (66, 'Phacelia incana Brand', 'Naja haje');
insert into quizzes (owner_id, title, description) values (67, 'Eleocharis palustris (L.) Roem. & Schult. var. vigens L.H. Bailey', 'Tetracerus quadricornis');
insert into quizzes (owner_id, title, description) values (68, 'Achnatherum caudatum (Trin.) S.L.W. Jacobs & J. Everett', 'Trichosurus vulpecula');
insert into quizzes (owner_id, title, description) values (69, 'Dichanthelium hirstii (Swallen) Kartesz', 'Macaca mulatta');
insert into quizzes (owner_id, title, description) values (70, 'Bergia texana (Hook.) Seub. ex Walp.', 'Mellivora capensis');
insert into quizzes (owner_id, title, description) values (71, 'Ribes cynosbati L.', 'Colobus guerza');
insert into quizzes (owner_id, title, description) values (72, 'Ceanothus papillosus Torr. & A. Gray', 'Ara chloroptera');
insert into quizzes (owner_id, title, description) values (73, 'Danthonia DC.', 'Thylogale stigmatica');
insert into quizzes (owner_id, title, description) values (74, 'Praxelis Cass.', 'Procyon lotor');
insert into quizzes (owner_id, title, description) values (75, 'Pulsatilla patens (L.) Mill. ssp. patens (L.) Mill. [excluded]', 'Cracticus nigroagularis');
insert into quizzes (owner_id, title, description) values (76, 'Turnera diffusa Willd. ex Schult.', 'Nasua nasua');
insert into quizzes (owner_id, title, description) values (77, 'Jarava plumosa (Spreng.) S.L.W. Jacobs & J. Everett', 'Coendou prehensilis');
insert into quizzes (owner_id, title, description) values (78, 'Piperia yadonii R. Morgan & Ackerman', 'Lasiodora parahybana');
insert into quizzes (owner_id, title, description) values (79, 'Cicer arietinum L.', 'Naja haje');
insert into quizzes (owner_id, title, description) values (80, 'Dryas L.', 'Rhea americana');
insert into quizzes (owner_id, title, description) values (81, 'Absconditella sphagnorum Vezda & Poelt', 'Damaliscus lunatus');
insert into quizzes (owner_id, title, description) values (82, 'Botrychium boreale Milde', 'Philetairus socius');
insert into quizzes (owner_id, title, description) values (83, 'Navarretia paradoxiclara L.A. Johnson & D. Gowen', 'Sarcophilus harrisii');
insert into quizzes (owner_id, title, description) values (84, 'Phaeosporobolus D. Hawksw. & Hafellner', 'Bucorvus leadbeateri');
insert into quizzes (owner_id, title, description) values (85, 'Bromus briziformis Fisch. & C.A. Mey.', 'Rangifer tarandus');
insert into quizzes (owner_id, title, description) values (86, 'Carex emoryi Dewey', 'Myrmecophaga tridactyla');
insert into quizzes (owner_id, title, description) values (87, 'Hieracium gracile Hook. var. gracile', 'Phoenicopterus chilensis');
insert into quizzes (owner_id, title, description) values (88, 'Rubus occidentalis L.', 'Ramphastos tucanus');
insert into quizzes (owner_id, title, description) values (89, 'Lupinus nanus Douglas ex Benth.', 'Oncorhynchus nerka');
insert into quizzes (owner_id, title, description) values (90, 'Lecanora glaucopsina Nyl.', 'Spheniscus magellanicus');
insert into quizzes (owner_id, title, description) values (91, 'Tagetes lemmonii A. Gray', 'Aonyx capensis');
insert into quizzes (owner_id, title, description) values (92, 'Atriplex torreyi (S. Watson) S. Watson', 'Bassariscus astutus');
insert into quizzes (owner_id, title, description) values (93, 'Isoetes bolanderi Engelm.', 'Arctogalidia trivirgata');
insert into quizzes (owner_id, title, description) values (94, 'Oncidium floridanum Ames', 'Rhabdomys pumilio');
insert into quizzes (owner_id, title, description) values (95, 'Astragalus serenoi (Kuntze) Sheldon var. sordescens Barneby', 'Pycnonotus nigricans');
insert into quizzes (owner_id, title, description) values (96, 'Festuca pseudovivipara (Pavlick) Pavlick', 'Macropus robustus');
insert into quizzes (owner_id, title, description) values (97, 'Diervilla sessilifolia Buckley', 'Lybius torquatus');
insert into quizzes (owner_id, title, description) values (98, 'Alyxia stellata (J.R. Forst. & G. Forst.) Roem. & Schult.', 'Aonyx capensis');
insert into quizzes (owner_id, title, description) values (99, 'Harrisia Britton', 'Dendrocygna viduata');
insert into quizzes (owner_id, title, description) values (100, 'Betula pumila L.', 'Crotalus cerastes');
