INSERT INTO quizzes (owner_id, title, description)
  VALUES
  ('1','In the animation film “Finding Nemo,” the main protagonist is a pufferfish.','FALSE'),
  ('1','Is Mount Kilimanjaro the world’s tallest peak?','FALSE'),
  ('1','Friends star Lisa Kudrow was originally cast in the sitcom Frasier.','FALSE'),
  ('1','If you’re born between May 1st and 20th, then you’re a Gemini','FALSE'),
  ('1','Emma Roberts is the daughter of Julia Roberts','FALSE'),
  ('1','There are over 2,500 stars on the Hollywood Walk of Fame','FALSE'),
  ('1','Fruit flies were the first living creatures sent into space','FALSE'),
  ('1','Cyclones spin in a clockwise direction in the southern hemisphere','FALSE'),
  ('1','Goldfish only have a memory of three seconds','FALSE'),
  ('1','The capital of Libya is Benghazi','FALSE'),
  ('1','Dolly Parton is the godmother of Miley Cyrus
','FALSE'),
  ('1','Roger Federer has won the most Wimbledon titles of any player
','FALSE'),
  ('1','An octopus has five hearts
','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE'),
  ('1','','FALSE');
