INSERT INTO questions (quiz_id, question)
  VALUES
  (1, 'Friends star Lisa Kudrow was originally cast in the sitcom Frasier'),
  (1, 'If you are born between May 1st and 20th, then you are a Gemini'),
  (1, 'Emma Roberts is the daughter of Julia Roberts'),
  (1, 'There are over 2,500 stars on the Hollywood Walk of Fame'),
  (2, 'Fruit flies were the first living creatures sent into space'),
  (2, 'Cyclones spin in a clockwise direction in the southern hemisphere'),
  (3, 'Goldfish only have a memory of three seconds'),
  (3, 'The capital of Libya is Benghazi'),
  (4, 'Dolly Parton is the godmother of Miley Cyrus'),
  (5, 'Roger Federer has won the most Wimbledon titles of any player'),
  (5, 'An octopus has five hearts'),
  (5, 'Brazil is the only country in the Americas to have the official language of Portuguese'),
  (5, 'The Channel Tunnel is the longest rail tunnel in the world'),
  (5, 'Darth Vader famously says the line Luke, I am your father in The Empire Strikes Back'),
  (5, 'Olivia Newton-John represented the UK in the Eurovision Song Contest in 1974, the year ABBA won with Waterloo'),
  (6, 'Stephen Hawking declined a knighthood from the Queen'),
  (6, 'The highest mountain in England is Ben Nevis'),
  (6, 'Nicolas Cage and Michael Jackson both married the same woman'),
  (6, 'Japan and Russia did not sign a peace treaty after World War Two so are technically still at war'),
  (7, 'The mathematical name for the shape of a Pringle is hyperbolic paraboloid'),
  (7, 'Charlie Chaplin came first in a Charlie Chaplin look-alike contest'),
  (7, 'Michael Keaton’s real name is Michael Douglas'),
  (7, 'Napoleon was of below-average height'),
  (7, 'Donald Duck’s middle name is Fauntelroy'),
  (8, 'The Statue of Liberty was a gift from France'),
  (8, 'According to Scottish law, it is illegal to be drunk in charge of a cow'),
  (8, 'The Great Wall of China is visible from space'),
  (8, 'The first tea bags were made of silk'),
  (8, 'Meghan Markle’s first name is Rachel'),
  (9, 'Warsaw is the capital of Bulgaria'),
  (9, 'A metre is further than a yard'),
  (9, 'A woman has walked on the moon'),
  (9, 'Flying in an aeroplane is statistically safer than driving in a car'),
  (9, 'The Big Apple is a nickname given to Washington D.C in 1971.'),
  (10, 'Muddy York is a nickname for New York in the Winter.'),
  (10, 'Peanuts are not nuts!'),
  (10, 'People may sneeze or cough while sleeping deeply.'),
  (10, 'Copyrights depreciate over time.'),
  (10, 'Emus can’t fly.'),
  (11, 'Electrons move faster than the speed of light.'),
  (11, 'There is no snow on Minecraft.'),
  (11, 'Light travels in a straight line.'),
  (11, 'The Mona Liza was stolen from the Louvre in 1911.'),
  (11, 'Janet Jackson performed at halftime of Super Bowl LV.'),
  (12, 'The Los Angeles Lakers won the 2020 NBA Championship.'),
  (12, 'Hamilton the musical is the first Broadway show ever written about Hamilton.'),
  (12, 'The film Moneyball is based on a true story.'),
  (12, 'The term inflation refers to a general fall in the prices of most products and services.'),
  (12, 'A credit card and a debit card are the same.'),
  (13, 'Ethereum is the second-largest cryptocurrency after Bitcoin.'),
  (13, 'There are three rivers in Saudi Arabia.'),
  (13, 'The Atlantic Ocean is the warmest in the world.'),
  (13, 'When the Eiffel Tower was unveiled, the Parisian art community hated it.'),
  (13, 'There are more ancient pyramids in Sudan than in Egypt.'),
  (14, 'Queen Elizabeth the 1st was the daughter of King Henry the 8th of England'),
  (14, 'Vitamin C is also known by the chemical name of Ascorbic Acid'),
  (14, 'The Nobel prize-winning novel ‘The Old Man and the Sea’ was written by the American author John Steinbeck'),
  (15, 'Rapper Nicki Minaj is over 180 cm 5 ft, 10.9 in in height'),
  (15, 'In theory, it takes over 5,000 helium balloons to lift an average-sized human from the ground'),
  (16, 'The Pan American Highway in the U.S.A. is the world’s longest highway'),
  (16, 'Transylvania is a historical region located in central Romania'),
  (16, 'Disabled Valery Spiridonov was the first person in the world to have his head transplanted onto another body'),
  (16, 'The maximum length for a video posted on TikTok is 60 seconds'),
  (16, 'Glass is manufactured mainly from processed sand'),
  (17, 'Actress Marilyn Monroe had 3 children resulting from her 3 marriages'),
  (17, 'Popping your finger or toe knuckles is bad for your joints'),
  (17, 'The Trojan horse was used by the Greeks to mask their way into the city of Troy and win the war'),
  (17, 'There are 6 naturally occurring noble gases in the periodic table of chemical elements'),
  (17, 'The liver is the largest organ in the human body'),
  (18, 'Singer and actress Miley Cyrus is an only child'),
  (18, 'There are over 30,000 varieties of apples existing in the world'),
  (18, 'Harry Potter’s first flying broomstick is called Firebolt'),
  (18, 'The U.S.A.’s southernmost state is Texas'),
  (18, 'The world’s earliest surviving motion-picture film dates back to 1888'),
  (19, 'Confucius is a world-renowned Latin philosopher '),
  (19, 'Footballer Cristiano Ronaldo is the most-followed person on Instagram and Facebook (in 2021)'),
  (19, 'Insulin was discovered by physiologist and professor of medicine Nicolae Paulescu'),
  (19, 'Real Madrid football club’s biggest rival is Atlético Madrid'),
  (19, 'Thomas Jefferson was the second president of the U.S.A.'),
  (20, 'There is no way of telling boiled eggs from raw eggs until you break them open'),
  (20, 'Dan Brown’s novel ‘Inferno’ was inspired by Dante Alighieri’s poem ‘Inferno’'),
  (20, 'Singer Billie Eilish’s full name is Billie Eilish Pirate Baird O’Connell'),
  (20, 'Manchester United football club has never won the UEFA Champions League trophy'),
  (20, 'Magician Richard Jones is the 10th winner of the TV show Britain’s got Talent'),
  (21, 'Mount Fuji is the highest mountain in Japan'),
  (21, 'Steak contains more protein than a regular-sized broccoli'),
  (21, 'TV series Game of Thrones – Tyrion Lannister’s favourite quote is ‘I drink, and I know things’'),
  (21, 'Pirates believed that having a ‘calico’ (three-coloured) cat on board of the ship brings bad luck'),
  (21, 'Pirates believed that having a ‘calico’ (three-coloured) cat on board of the ship brings bad luck'),
  (22, 'The world’s longest word has no less than 189,819 letters and comes from the English language'),
  (22, 'Athlete Usain Bolt is faster than a cheetah'),
  (22, 'Indira Gandhi was the first female Prime Minister of India'),
  (22, 'The lighter was invented before the matches'),
  (22, 'The oldest educational establishment in the world is the University of Al Quaraouiyine in Morocco '),
  (23, '‘Braveheart’ and ‘The English patient’ have competed for the ‘Academy Award Best Picture’ award in the same year'),
  (23, 'The first football in the world was manufactured from a pig’s bladder'),
  (23, 'The X-Factor TV show first aired in the U.S.A. in 2004'),
  (23, 'Just like humans, dogs can be left-pawed or right-pawed'),
  (23, 'Rio de Janeiro is the capital city of Brazil'),
  (24, 'Although they love to drink it, cats are lactose intolerant to cow’s milk'),
  (24, 'Grapefruit can cause poisoning if consumed with some prescribed drugs'),
  (24, 'Except for humans, crows and ravens are the most intelligent creatures in the world'),
  (24, 'The world’s best-selling music album of all times belongs to The Beatles'),
  (24, 'The spiral shapes of sunflowers follow the Fibonacci sequence (where each number is the sum of the last 2) to maximize sunlight intake'),
  (25, 'Evita Perón was the first female president of Argentina'),
  (25, 'A human being can live up to 3 weeks without drinking water'),
  (25, 'Writer Agatha Christies real name is Mary Westmacott');
