DROP TABLE IF EXISTS previous_attempts CASCADE;

CREATE TABLE previous_attempts (
  id SERIAL PRIMARY KEY NOT NULL,
  FK quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  FK user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  score INTEGER
);
